url:
baseurl:

# Site settings
title: Openscapes Champions Summit
email: your-email@domain.com
description: "Information and links from the  Openscapes Champions Summit 2019"

# Team names, titles and social links
people:
- name: Halley Froehlich
  pic: Halley
  position: Openscapes Champion
  text: Dr. Froehlich is a marine aquaculture & fisheries scientist studying <a href="https://www.nature.com/articles/s41559-018-0669-1">global food systems and climate change</a>. She has put a strong emphasis on sharing her work with many audiences, including on Bill Nye the Science Guy. 
  social:
    - title: link
      url: https://halleyfroehlich.wordpress.com/
    - title: twitter
      url: https://twitter.com/DocFroehlich


- name: Chelsea Wood, PhD
  pic: Chelsea
  position: Openscapes Champion
  text: Cr. Wood is an ecologist studying marine and freshwater parasites and infectious disease in a changing world. 
  social:
    - title: link
      url: https://chelsealwood.wordpress.com/
    - title: twitter
      url: twitter.com/DrChelseaLWood


- name: Chelsea Wood, PhD
  pic: Chelsea
  position: Openscapes Champion
  text: Cr. Wood is an ecologist studying marine and freshwater parasites and infectious disease in a changing world. 
  social:
    - title: link
      url: https://chelsealwood.wordpress.com/
    - title: twitter
      url: twitter.com/DrChelseaLWood


- name: Alex Morley
  pic: Alex
  position: Neuroscientist
  text: I <a href="https://alexmorley.me/Back-Your-Scientific-Stack/">support</a> the development of software that is built around the needs of humans. I have been working with neuroscientists to build <a href="https://users.flatironinstitute.org/~magland/docs/"> an open platform </a> for automatically benchmarking analysis algorithms, with data scientists to write <a href="https://www.turing.ac.uk/research/research-projects/turing-way-handbook-reproducible-data-science"> a handbook for reproducible data science </a>and designers to build <a href="https://github.com/alexmorley/graphical-notebooks">a graphical interface for computational notebooks</a>.
  social:
    - title: twitter
      url: https://twitter.com/alex__morley
    - title: linkedin
      url: https://www.linkedin.com/in/alexanderjmorley
    - title: github
      url: https://github.com/alexmorley


- name: Ciera Martinez
  pic: Ciera
  position: Evolutionary Biologist
  text: One of the main missions of my work is to make scientific research and data more open and transparent. I do this by <a href="http://ropensci.github.io/reproducibility-guide/"> establishing best practices </a>, data standards, and <a href = "https://reproducible-science-curriculum.github.io/organization-RR-Jupyter/">creating education materials</a>.  This year I have been working on making natural history data more usable, accessible, and valued. Visit <a href = "https://curiositydata.org"> curiositydata.org </a> for more information on this project.
  social:
    - title: twitter
      url: twitter.com/CieraReports
    - title: github
      url: http://github.com/iamciera
    - title: linkedin
      url: https://www.linkedin.com/in/ciera-martinez-phd-b77432120/
    - title: link
      url: http://cierareports.org/cv/

- name: Daniela Saderi
  pic: Daniela
  position: Neuroscientist
  text: I am an open science advocate, passionate about research and making scientific output available to everyone to advance knowledgeand improve transparency. I recently co-founded <a href= "https://www.prereview.org/"> PREreview </a>, a community of researchers and a free online platform to post, read and engage with preprint reviews. Follow our progress on <a href = "https://github.com/PREreview"> Github</a> and on <a href = https://twitter.com/PREreview_> Twitter </a>.
  social:
    - title: twitter
      url: https://twitter.com/Neurosarda
    - title: github
      url: http://github.com/dasaderi
    - title: linkedin
      url: https://www.linkedin.com/in/daniela-saderi/

- name: Chelsea Wood, PhD
  pic: Chelsea
  position: Openscapes Champion
  text: Cr. Wood is an ecologist studying marine and freshwater parasites and infectious disease in a changing world. 
  social:
    - title: twitter
      url: twitter.com/DrChelseaLWood
    - title: link
      url: https://chelsealwood.wordpress.com/
   
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty
